### ISSUE TITLE
Known issue with Mac M1?

### ISSUE THREAD

**Issue by Fristi** [ChristopherDavenport/scala-native-ember-example#2]
Hi !

Super cool to have Scala go to bare metal!

I tried it on my amd64 machine (MacOS) works great there, but also tried it on my new M1 and during `sbt run` it fails with

```
[info] welcome to sbt 1.7.1 (Homebrew Java 18.0.1.1)
[info] loading global plugins from /Users/markie/.sbt/1.0/plugins
[info] loading settings for project scala-native-ember-example-build from plugins.sbt ...
[info] loading project definition from /Users/markie/Projects/scala-native-ember-example/project
[info] loading settings for project scala-native-ember-example from build.sbt ...
[info] set current project to Scala Native Ember Example (in build file:/Users/markie/Projects/scala-native-ember-example/)
[info] Linking (2639 ms)
[info] Discovered 6743 classes and 44040 methods
[info] Optimizing (debug mode) (4985 ms)
[info] Generating intermediate code (7295 ms)
[info] Produced 10 files
[info] Compiling to native code (3662 ms)
[error] ld: warning: directory not found for option '-L/usr/local/opt/openssl@1.1/lib'
[error] ld: library not found for -lcrypto
[error] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[error] Failed to link /Users/markie/Projects/scala-native-ember-example/target/scala-3.2.0/scala-native-ember-example-out
[error] (Compile / nativeLink) Failed to link /Users/markie/Projects/scala-native-ember-example/target/scala-3.2.0/scala-native-ember-example-out
```

I installed `brew install gsl openssl@1.1 s2n` .. but turns out `openssl version` returns `LibreSSL 2.8.3` which might be causing trouble ?

Is this something known?

**Comment by armanbilge** [comment]
@Fristi thanks for the report! I don't think this is an M1 issue. It looks like s2n recently updated to openssl@3 in https://github.com/Homebrew/homebrew-core/commit/d5a4f6a1ab89b65034ffd698e55736cea13eaa36.

So perhaps we need to update this line:
https://github.com/ChristopherDavenport/scala-native-ember-example/blob/3399f06c0db216bfdd6f40a95535a061d937b554/build.sbt#L31

Would you be able to give that a try and report back? Thanks!

**Comment by armanbilge** [comment]
Actually, it _might_ be an M1 issue. I remember reading something about brew installing libraries in a different location on M1 🤔 
```
[error] ld: warning: directory not found for option '-L/usr/local/opt/openssl@1.1/lib'
```

**Comment by armanbilge** [comment]
Ah yes indeed, that is it. I'm not entirely sure what we need to change that linking option to. Maybe this?
```
-L/opt/homebrew/opt/openssl@3/lib
```

See some discussion on the change here: https://earthly.dev/blog/homebrew-on-m1/

**Comment by Fristi** [comment]
That does the trick! Thanks a lot, pushed a PR :)
